Fix openvswtich script crash issue
When run openvswtich script "dpdk-pmdinfo.py", it will crash with Error:
"ImportError: cannot import name UBInt8". It is due to new python-construct
rpm remove UBInt8. Roll back python-construct to fix it.

Story: 2004522
Task: 29124

Change-Id: Iefa9d21bb81390b5bcf1d0605c0408b5869616f5
Signed-off-by: Shuicheng Lin <shuicheng.lin@intel.com>